media:
  input: src/assets/images/post-pics
  output: assets/images
content:
  - name: posts
    label: Posts
    path: src/content/blog
    type: collection
    view:
      fields: [title, published, pubDate]
    fields:
      - name: Draft
        label: draft
        type: boolean
        default: true
      - name: pubDate
        label: Publish Date
        type: date
      - name: updatedDate
        label: Updated Date
        type: date
      - name: Title
        label: title
        type: string
      - name: description
        label: Description
        type: rich-text
      - name: canonicalUrl
        label: Canonical URL
        type: string
