media:
  input: src/assets/images/post-pics
  output: assets/images
content:
  - name: posts
    label: Posts
    path: src/content/blog
    type: collection
    view:
      fields: [title, description, published, pubDate, updatedDate]
    fields:
      - name: Draft
        label: draft
        type: boolean
        default: true
      - name: Publish Date
        label: pubDate
        type: date
      - name: Updated Date
        label: updatedDate
        type: date
      - name: title
        label: Title
        type: string
      - name: Description
        label: description
        type: rich-text
      - name: Canonical URL
        label: canonicalUrl
        type: string
