media:
  input: src/assets/images/post-pics
  output: assets/images
content:
  - name: posts
    label: Posts
    path: src/posts
    type: collection
    view:
      fields: [title, published, date]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
